export const userInfo = {
  id: 'usr_001',
  name: 'Dr. Manish Sharma',
  image: 'https://randomuser.me/api/portraits/men/1.jpg',
  email: 'manish.doctor@example.com',
  phone: '9876543210',
  role: 'doctor',
  specialization: 'Cardiologist',
  licenseNumber: 'MED-IND-2026-001',
  experience: 8,
  bio: 'Experienced cardiologist focused on preventive heart care.',
  rating: 4.8,
  dateOfBirth: '1990-04-30',
  bloodType: 'O+',
  allergies: ['Penicillin'],
  medicalHistory: ['Hypertension'],
  createdAt: '2026-04-30T00:00:00.000Z',
  updatedAt: '2026-04-30T00:00:00.000Z',
};

export const doctorsAppointmentStatusData = [
  {
    id: 'status_001',
    status: 'approved',
    title: 'Approved',
    count: 3,
    backgroundColor: '#E8F5E9',
    borderColor: '#A5D6A7',
    textColor: '#2E7D32',
  },
  {
    id: 'status_002',
    status: 'pending',
    title: 'Pending',
    count: 3,
    backgroundColor: '#FFF8E1',
    borderColor: '#FFE082',
    textColor: '#F57F17',
  },
  {
    id: 'status_003',
    status: 'cancelled',
    title: 'Cancelled',
    count: 3,
    backgroundColor: '#FFEBEE',
    borderColor: '#EF9A9A',
    textColor: '#C62828',
  },
  {
    id: 'status_004',
    status: 'completed',
    title: 'Completed',
    count: 2,
    backgroundColor: '#E3F2FD',
    borderColor: '#90CAF9',
    textColor: '#1565C0',
  },
  {
    id: 'status_005',
    status: 'upcoming',
    title: 'Upcoming',
    count: 2,
    backgroundColor: '#F3E5F5',
    borderColor: '#CE93D8',
    textColor: '#6A1B9A',
  },
];

export const getAppointmentStatusCount = (
  appointmentStatusData: typeof doctorsAppointmentStatusData,
) => {
  return appointmentStatusData.reduce<Record<string, number>>((acc, item) => {
    acc[item.status] = item.count;
    return acc;
  }, {});
};

export const todayAppointmentsData = [
  {
    id: 'today_001',
    patientName: 'Eleanor Shellstrop',
    appointmentTime: '09:30',
    concern: 'Chest Pain Investigation',
    visitType: 'Follow-up',
    status: 'today',
    tagBackgroundColor: '#FFF3E8',
    tagTextColor: '#F05A28',
    timeBackgroundColor: '#DDE7FF',
  },
  {
    id: 'today_002',
    patientName: 'Chidi Anagonye',
    appointmentTime: '10:15',
    concern: 'Routine ECG Analysis',
    visitType: 'Consultation',
    status: 'today',
    tagBackgroundColor: '#E7FAF6',
    tagTextColor: '#068D7D',
    timeBackgroundColor: '#E4ECFF',
  },
  {
    id: 'today_003',
    patientName: 'Tahani Al-Jamil',
    appointmentTime: '12:00',
    concern: 'Blood Pressure Review',
    visitType: 'Checkup',
    status: 'today',
    tagBackgroundColor: '#EEF5FF',
    tagTextColor: '#276EF1',
    timeBackgroundColor: '#DDE7FF',
  },
];

export const upcomingAppointmentsData = [
  {
    id: 'upcoming_001',
    patientName: 'Jason Mendoza',
    appointmentTime: '14:30',
    concern: 'Heart Rhythm Assessment',
    visitType: 'Consultation',
    status: 'upcoming',
    tagBackgroundColor: '#E7FAF6',
    tagTextColor: '#068D7D',
    timeBackgroundColor: '#DDE7FF',
  },
  {
    id: 'upcoming_002',
    patientName: 'Simone Garnett',
    appointmentTime: '16:00',
    concern: 'Medication Review',
    visitType: 'Follow-up',
    status: 'upcoming',
    tagBackgroundColor: '#FFF3E8',
    tagTextColor: '#F05A28',
    timeBackgroundColor: '#E4ECFF',
  },
  {
    id: 'upcoming_003',
    patientName: 'Michael Realman',
    appointmentTime: '17:45',
    concern: 'Cardiac Health Screening',
    visitType: 'Screening',
    status: 'upcoming',
    tagBackgroundColor: '#F3E5F5',
    tagTextColor: '#6A1B9A',
    timeBackgroundColor: '#DDE7FF',
  },
];

export const completedAppointmentsData = [
  {
    id: 'completed_001',
    patientName: 'Janet Della',
    appointmentTime: '08:45',
    concern: 'Post-treatment Review',
    visitType: 'Completed',
    status: 'completed',
    tagBackgroundColor: '#E8F5E9',
    tagTextColor: '#2E7D32',
    timeBackgroundColor: '#E4ECFF',
  },
  {
    id: 'completed_002',
    patientName: 'Brent Norwalk',
    appointmentTime: '11:20',
    concern: 'Lab Results Review',
    visitType: 'Completed',
    status: 'completed',
    tagBackgroundColor: '#E8F5E9',
    tagTextColor: '#2E7D32',
    timeBackgroundColor: '#DDE7FF',
  },
  {
    id: 'completed_003',
    patientName: 'Mindy St. Claire',
    appointmentTime: '15:10',
    concern: 'Lifestyle Consultation',
    visitType: 'Completed',
    status: 'completed',
    tagBackgroundColor: '#E8F5E9',
    tagTextColor: '#2E7D32',
    timeBackgroundColor: '#E4ECFF',
  },
];

export const cancelledAppointmentsData = [
  {
    id: 'cancelled_001',
    patientName: 'Pillboi Patel',
    appointmentTime: '10:45',
    concern: 'Routine Consultation',
    visitType: 'Cancelled',
    status: 'cancelled',
    tagBackgroundColor: '#FFEBEE',
    tagTextColor: '#C62828',
    timeBackgroundColor: '#DDE7FF',
  },
  {
    id: 'cancelled_002',
    patientName: 'Shawn Vicky',
    appointmentTime: '13:30',
    concern: 'Palpitation Complaint',
    visitType: 'Cancelled',
    status: 'cancelled',
    tagBackgroundColor: '#FFEBEE',
    tagTextColor: '#C62828',
    timeBackgroundColor: '#E4ECFF',
  },
  {
    id: 'cancelled_003',
    patientName: 'Trevor Adams',
    appointmentTime: '18:00',
    concern: 'ECG Report Discussion',
    visitType: 'Cancelled',
    status: 'cancelled',
    tagBackgroundColor: '#FFEBEE',
    tagTextColor: '#C62828',
    timeBackgroundColor: '#DDE7FF',
  },
];
